sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - vendor
    - zf-mkdoc-theme

env:
  global:
    - SITE_URL: https://zendframework.github.io/zend-expressive
    - GH_USER_NAME: "Matthew Weier O'Phinney"
    - GH_USER_EMAIL: matthew@weierophinney.net
    - GH_REF: github.com/zendframework/zend-expressive.git
    - secure: "djSWIzje6Y+r72owunmsiCxNlXm1pmnlwMdjhy3L8g9lSnShC7MFvHBhhvEBQgVkKIxjmzq6RPI5wH/+LcotsHsM+LgVsgNhr9B9OR82Y3BNZM+bCU6qKmLWKn2bFafF097VBt22VaggFFlJhifWdCHZ65xfBIXXEACTDLm1nbOL9aKryEpsGTyd/NUyRLPyc9ShoVgHo/6I+NXHGbADxLGokdnQDw4kUpjWs++/G490OrkY8rZHDD2TpCcPca/v7i1+RrJVLnFVhXBAzSmxFLQon+FVN6orhiONs9r8u/sNovQtAEpaO4hmn8LFrf0oK/d4CgNdvm+1CQt+3TWJOM/yqYxOVxB9WukWfeGLn1d/XZvr9pUuF1BAP0r1kd95ewXgSwG9H5CCSBer39c+NnVTHE0PHUSaL0YX5VuOlAJ9K/suxHkRzQroJkkx34hI7EsJYsoMXrxBll7t5l9J8EQNGeihMc81pBWS262PyAlJxDtZ3aJpoVhhrVRpBdKNhXPFi5/nBb8EFxQUIAzYOSPJjbzJZxNBfB13Mq9Qn9WeEtw25QnHY60FmiVTs7hPCuMFOnUrJD+dW4Rkj86GBMecihdB/8TfYFvr6742rMZ+x6KhbyGOJADhp06YJC/2zPfpGzvWR8QqGDfDhXQAS7QNj/yH72OVIwUkC4oePfI="

matrix:
  fast_finish: true
  include:
    - php: 5.5
      env:
        - EXECUTE_CS_CHECK=true
    - php: 5.6
      env:
        - EXECUTE_TEST_COVERALLS=true
        - DEPLOY_DOCS="$(if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then echo -n 'true' ; else echo -n 'false' ; fi)"
        - PATH="$HOME/.local/bin:$PATH"
    - php: 7
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - composer self-update
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer require --dev --no-update satooshi/php-coveralls:dev-master ; fi

install:
  - travis_retry composer install --no-interaction
  - composer info -i

script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer test-coverage ; fi
  - if [[ $EXECUTE_TEST_COVERALLS != 'true' ]]; then composer test ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer cs ; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then composer license-check ; fi
  - if [[ $DEPLOY_DOCS == "true" && "$TRAVIS_TEST_RESULT" == "0" ]]; then wget -O theme-installer.sh "https://raw.githubusercontent.com/zendframework/zf-mkdoc-theme/master/theme-installer.sh" ; chmod 755 theme-installer.sh ; ./theme-installer.sh ; fi

after_script:
  - if [[ $EXECUTE_TEST_COVERALLS == 'true' ]]; then composer coveralls ; fi

after_success:
  - if [[ $DEPLOY_DOCS == "true" ]]; then echo "Preparing to build and deploy documentation" ; ./zf-mkdoc-theme/deploy.sh ; echo "Completed deploying documentation" ; fi

notifications:
  email: true
