docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - 'Getting Started':
        - 'Overview and Features': v3/getting-started/features.md
        - 'Quick Start': v3/getting-started/quick-start.md
    - Features:
        - "Middleware Types": v3/features/middleware-types.md
        - Applications: v3/features/application.md
        - Containers:
            - Introduction: v3/features/container/intro.md
            - 'Container Factories': v3/features/container/factories.md
            - 'Delegator Factories': v3/features/container/delegator-factories.md
            - 'The Middleware Container': v3/features/container/middleware-container.md
            - 'The Middleware Factory': v3/features/container/middleware-factory.md
            - 'Using zend-servicemanager': v3/features/container/zend-servicemanager.md
            - 'Using Pimple': v3/features/container/pimple.md
            - 'Using Aura.Di': v3/features/container/aura-di.md
            - 'Container configuration': v3/features/container/config.md
        - 'Routing Adapters':
            - Introduction: v3/features/router/intro.md
            - 'Routing Interface': v3/features/router/interface.md
            - 'The Route Collector': v3/features/router/route-collector.md
            - 'URI Generation': v3/features/router/uri-generation.md
            - 'Routing vs Piping': v3/features/router/piping.md
            - 'Using Aura': v3/features/router/aura.md
            - 'Using FastRoute': v3/features/router/fast-route.md
            - 'Using zend-router': v3/features/router/zf2.md
        - Templating:
            - Introduction: v3/features/template/intro.md
            - 'Template Renderer Interface': v3/features/template/interface.md
            - 'Templated Request Handlers': v3/features/template/request-handlers.md
            - 'Using Plates': v3/features/template/plates.md
            - 'Using Twig': v3/features/template/twig.md
            - 'Using zend-view': v3/features/template/zend-view.md
        - 'Error Handling': v3/features/error-handling.md
        - 'Modular Applications': v3/features/modular-applications.md
        - Middleware:
            - 'Routing and Dispatch Middleware': v3/features/middleware/routing-and-dispatch-middleware.md
            - 'Implicit HEAD and OPTIONS Middleware': v3/features/middleware/implicit-methods-middleware.md
            - 'Returning Method Not Allowed': v3/features/middleware/method-not-allowed-middleware.md
        - Helpers:
            - Introduction: v3/features/helpers/intro.md
            - UrlHelper: v3/features/helpers/url-helper.md
            - ServerUrlHelper: v3/features/helpers/server-url-helper.md
            - 'Body Parsing Middleware': v3/features/helpers/body-parse.md
            - 'Content-Length Middleware': v3/features/helpers/content-length.md
        - Emitters: v3/features/emitters.md
    - Cookbook:
        - 'Autowiring routes and pipeline middleware': v3/cookbook/autowiring-routes-and-pipelines.md
        - 'Using Expressive from a subdirectory': v3/cookbook/using-a-base-path.md
        - 'Prepending a common path to all routes': v3/cookbook/common-prefix-for-routes.md
        - 'Passing data between middleware': v3/cookbook/passing-data-between-middleware.md
        - 'Route-specific middleware pipelines': v3/cookbook/route-specific-pipeline.md
        - 'Segregating middleware by host': v3/cookbook/host-segregated-middleware.md
        - 'Using double-pass middleware': v3/cookbook/double-pass-middleware.md
        - 'Setting a locale based on a routing parameter': v3/cookbook/setting-locale-depending-routing-parameter.md
        - 'Setting a locale without a routing parameter': v3/cookbook/setting-locale-without-routing-parameter.md
        - 'Enabling debug toolbars': v3/cookbook/debug-toolbars.md
        - 'Flash Messengers': v3/cookbook/flash-messengers.md
        - 'Registering custom view helpers when using zend-view': v3/cookbook/using-custom-view-helpers.md
        - 'Using zend-form view helpers': v3/cookbook/using-zend-form-view-helpers.md
    - Reference:
        - "Why choose Expressive?": v3/why-expressive.md
        - "CLI Tooling": v3/reference/cli-tooling.md
        - 'Expressive Projects': v3/reference/expressive-projects.md
        - Migration: v3/reference/migration.md
    - v2:
        - v2/index.md
        - 'Getting Started':
            - 'Overview and Features': v2/getting-started/features.md
            - 'Quick Start: Standalone': v2/getting-started/standalone.md
            - 'Quick Start: Skeleton Installer': v2/getting-started/skeleton.md
        - Features:
            - "Middleware Types": v2/features/middleware-types.md
            - Applications: v2/features/application.md
            - Containers:
                - Introduction: v2/features/container/intro.md
                - 'Container Factories': v2/features/container/factories.md
                - 'Delegator Factories': v2/features/container/delegator-factories.md
                - 'Using zend-servicemanager': v2/features/container/zend-servicemanager.md
                - 'Using Pimple': v2/features/container/pimple.md
                - 'Using Aura.Di': v2/features/container/aura-di.md
            - 'Routing Adapters':
                - Introduction: v2/features/router/intro.md
                - 'Routing Interface': v2/features/router/interface.md
                - 'URI Generation': v2/features/router/uri-generation.md
                - 'Routing vs Piping': v2/features/router/piping.md
                - 'Using Aura': v2/features/router/aura.md
                - 'Using FastRoute': v2/features/router/fast-route.md
                - 'Using the ZF2 Router': v2/features/router/zf2.md
            - Templating:
                - Introduction: v2/features/template/intro.md
                - 'Template Renderer Interface': v2/features/template/interface.md
                - 'Templated Middleware': v2/features/template/middleware.md
                - 'Using Plates': v2/features/template/plates.md
                - 'Using Twig': v2/features/template/twig.md
                - 'Using zend-view': v2/features/template/zend-view.md
            - 'Error Handling': v2/features/error-handling.md
            - 'Modular Applications': v2/features/modular-applications.md
            - Middleware:
                - 'Implicit HEAD and OPTIONS Middleware': v2/features/middleware/implicit-methods-middleware.md
            - Helpers:
                - Introduction: v2/features/helpers/intro.md
                - UrlHelper: v2/features/helpers/url-helper.md
                - ServerUrlHelper: v2/features/helpers/server-url-helper.md
                - 'Body Parsing Middleware': v2/features/helpers/body-parse.md
                - 'Content-Length Middleware': v2/features/helpers/content-length.md
            - Emitters: v2/features/emitters.md
        - Cookbook:
            - 'Autowiring routes and pipeline middleware': v2/cookbook/autowiring-routes-and-pipelines.md
            - 'Prepending a common path to all routes': v2/cookbook/common-prefix-for-routes.md
            - 'Route-specific middleware pipelines': v2/cookbook/route-specific-pipeline.md
            - 'Registering custom view helpers when using zend-view': v2/cookbook/using-custom-view-helpers.md
            - 'Using zend-form view helpers': v2/cookbook/using-zend-form-view-helpers.md
            - 'Using Expressive from a subdirectory': v2/cookbook/using-a-base-path.md
            - 'Setting a locale based on a routing parameter': v2/cookbook/setting-locale-depending-routing-parameter.md
            - 'Setting a locale without a routing parameter': v2/cookbook/setting-locale-without-routing-parameter.md
            - 'Enabling debug toolbars': v2/cookbook/debug-toolbars.md
            - 'Handling multiple routes in a single class': v2/cookbook/using-routed-middleware-class-as-controller.md
            - 'Flash Messengers': v2/cookbook/flash-messengers.md
            - 'Passing data between middleware': v2/cookbook/passing-data-between-middleware.md
        - Reference:
            - "Why choose Expressive?": v2/why-expressive.md
            - "CLI Tooling": v2/reference/cli-tooling.md
            - Examples: v2/reference/usage-examples.md
            - 'Expressive Projects': v2/reference/expressive-projects.md
            - Migration:
                - "To version 2": v2/reference/migration.md
                - "To version 2.2": v2/reference/migration-to-v2-2.md
    - v1:
        - v1/index.md
        - 'Getting Started':
            - 'Overview and Features': v1/getting-started/features.md
            - 'Quick Start: Standalone': v1/getting-started/standalone.md
            - 'Quick Start: Skeleton Installer': v1/getting-started/skeleton.md
        - Features:
            - Applications: v1/features/application.md
            - Containers:
                - Introduction: v1/features/container/intro.md
                - 'Container Factories': v1/features/container/factories.md
                - 'Using zend-servicemanager': v1/features/container/zend-servicemanager.md
                - 'Using Pimple': v1/features/container/pimple.md
                - 'Using Aura.Di': v1/features/container/aura-di.md
            - 'Routing Adapters':
                - Introduction: v1/features/router/intro.md
                - 'Routing Interface': v1/features/router/interface.md
                - 'URI Generation': v1/features/router/uri-generation.md
                - 'Routing vs Piping': v1/features/router/piping.md
                - 'Using Aura': v1/features/router/aura.md
                - 'Using FastRoute': v1/features/router/fast-route.md
                - 'Using the ZF2 Router': v1/features/router/zf2.md
            - Templating:
                - Introduction: v1/features/template/intro.md
                - 'Template Renderer Interface': v1/features/template/interface.md
                - 'Templated Middleware': v1/features/template/middleware.md
                - 'Using Plates': v1/features/template/plates.md
                - 'Using Twig': v1/features/template/twig.md
                - 'Using zend-view': v1/features/template/zend-view.md
            - 'Error Handling': v1/features/error-handling.md
            - Helpers:
                - Introduction: v1/features/helpers/intro.md
                - UrlHelper: v1/features/helpers/url-helper.md
                - ServerUrlHelper: v1/features/helpers/server-url-helper.md
                - 'Body Parsing Middleware': v1/features/helpers/body-parse.md
            - Emitters: v1/features/emitters.md
        - Cookbook:
            - 'Prepending a common path to all routes': v1/cookbook/common-prefix-for-routes.md
            - 'Route-specific middleware pipelines': v1/cookbook/route-specific-pipeline.md
            - 'Setting custom 404 page handling': v1/cookbook/custom-404-page-handling.md
            - 'Registering custom view helpers when using zend-view': v1/cookbook/using-custom-view-helpers.md
            - 'Using zend-form view helpers': v1/cookbook/using-zend-form-view-helpers.md
            - 'Using Expressive from a subdirectory': v1/cookbook/using-a-base-path.md
            - 'Building modular applications': v1/cookbook/modular-layout.md
            - 'Setting a locale based on a routing parameter': v1/cookbook/setting-locale-depending-routing-parameter.md
            - 'Setting a locale without a routing parameter': v1/cookbook/setting-locale-without-routing-parameter.md
            - 'Enabling debug toolbars': v1/cookbook/debug-toolbars.md
            - 'Handling multiple routes in a single class': v1/cookbook/using-routed-middleware-class-as-controller.md
            - 'Flash Messengers': v1/cookbook/flash-messengers.md
        - Reference:
            - "Why choose Expressive?": v1/why-expressive.md
            - Examples: v1/reference/usage-examples.md
            - 'Expressive Projects': v1/reference/expressive-projects.md
            - Migration:
                - 'From RC5 and Earlier': v1/reference/migration/rc-to-v1.md
                - 'To Expressive 1.1': v1/reference/migration/to-v1-1.md
    - "_hidden-legacy-page-links":
            - '_getting_started_overview': getting-started/features.md
            - '_getting_started_standalone': getting-started/standalone.md
            - '_getting_started_skeleton': getting-started/skeleton.md
            - '_features_middleware_types': features/middleware-types.md
            - '_features_application': features/application.md
            - '_features_container_intro': features/container/intro.md
            - '_features_container_factories': features/container/factories.md
            - '_features_container_delegator_factories': features/container/delegator-factories.md
            - '_features_container_using_zend-servicemanager': features/container/zend-servicemanager.md
            - '_features_container_using_pimple': features/container/pimple.md
            - '_features_container_using_aura.di': features/container/aura-di.md
            - '_features_router_introduction': features/router/intro.md
            - '_features_router_interface': features/router/interface.md
            - '_features_router_uri_generation': features/router/uri-generation.md
            - '_features_router_piping': features/router/piping.md
            - '_features_router_using_aura': features/router/aura.md
            - '_features_router_using_fastroute': features/router/fast-route.md
            - '_features_router_using_the ZF2 Router': features/router/zf2.md
            - '_features_template_intro': features/template/intro.md
            - '_features_template_interface': features/template/interface.md
            - '_features_template_middleware': features/template/middleware.md
            - '_features_template_plates': features/template/plates.md
            - '_features_template_twig': features/template/twig.md
            - '_features_template_zend-view': features/template/zend-view.md
            - '_features_error_handling': features/error-handling.md
            - '_features_modular_applications': features/modular-applications.md
            - '_features_middleware_implicit_head_and_options_middleware': features/middleware/implicit-methods-middleware.md
            - '_features_helpers_intro': features/helpers/intro.md
            - '_features_helpers_urlhelper': features/helpers/url-helper.md
            - '_features_helpers_serverurlhelper': features/helpers/server-url-helper.md
            - '_features_helpers_body_parsing_middleware': features/helpers/body-parse.md
            - '_features_helpers_content_length_middleware': features/helpers/content-length.md
            - '_features_emitters': features/emitters.md
            - '_cookbook_autowiring_routes_and_pipeline_middleware': cookbook/autowiring-routes-and-pipelines.md
            - '_cookbook_prepending_a_common_path_to_all_routes': cookbook/common-prefix-for-routes.md
            - '_cookbook_route-specific_middleware_pipelines': cookbook/route-specific-pipeline.md
            - '_cookbook_setting_custom_404_page_handling': cookbook/custom-404-page-handling.md
            - '_cookbook_registering_custom_view_helpers_when_using_zend-view': cookbook/using-custom-view-helpers.md
            - '_cookbook_using_zend-form_view_helpers': cookbook/using-zend-form-view-helpers.md
            - '_cookbook_using_Expressive_from_a_subdirectory': cookbook/using-a-base-path.md
            - '_cookbook_building_modular_applications': cookbook/modular-layout.md
            - '_cookbook_setting_a_locale_based_on_a_routing_parameter': cookbook/setting-locale-depending-routing-parameter.md
            - '_cookbook_setting_a_locale_without_a_routing_parameter': cookbook/setting-locale-without-routing-parameter.md
            - '_cookbook_enabling_debug_toolbars': cookbook/debug-toolbars.md
            - '_cookbook_handling_multiple_routes_in_a_single_class': cookbook/using-routed-middleware-class-as-controller.md
            - '_cookbook_flash_messengers': cookbook/flash-messengers.md
            - '_cookbook_passing_data_between_middleware': cookbook/passing-data-between-middleware.md
            - "_reference_why_expressive?": why-expressive.md
            - "_reference_cli_tooling": reference/cli-tooling.md
            - '_reference_usage_examples': reference/usage-examples.md
            - '_reference_expressive_Projects': reference/expressive-projects.md
            - '_migration_to_v2': reference/migration/to-v2.md
            - '_migration_from_rc5_and_earlier': reference/migration/rc-to-v1.md
            - '_migration_to_expressive_1.1': reference/migration/to-v1-1.md
site_name: Expressive
site_description: 'zend-expressive: PSR-7 Middleware Microframework'
repo_url: 'https://github.com/zendframework/zend-expressive'
copyright: 'Copyright (c) 2015-2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'
extra_css:
    - css/zend-expressive.css
