docs_dir: doc/book
site_dir: doc/html
pages:
    - index.md
    - { 'Overview and Features': features.md }
    - { 'Quick Start: Skeleton + Installer': quick-start-skeleton.md }
    - { 'Quick Start: Standalone': quick-start.md }
    - { Applications: application.md }
    - { Containers: [{ Introduction: container/intro.md }, { 'Container Factories': container/factories.md }, { 'Using zend-servicemanager': container/zend-servicemanager.md }, { 'Using Pimple': container/pimple.md }, { 'Using Aura.Di': container/aura-di.md }] }
    - { 'Routing Adapters': [{ Introduction: router/intro.md }, { 'Routing Interface': router/interface.md }, { 'URI Generation': router/uri-generation.md }, { 'Route Result Observers': router/result-observers.md }, { 'Routing vs Piping': router/piping.md }, { 'Using Aura': router/aura.md }, { 'Using FastRoute': router/fast-route.md }, { 'Using the ZF2 Router': router/zf2.md }] }
    - { Templating: [{ Introduction: template/intro.md }, { 'Template Renderer Interface': template/interface.md }, { 'Templated Middleware': template/middleware.md }, { 'Using Plates': template/plates.md }, { 'Using Twig': template/twig.md }, { 'Using zend-view': template/zend-view.md }] }
    - { 'Error Handling': error-handling.md }
    - { Helpers: [{ Introduction: helpers/intro.md }, { UrlHelper: helpers/url-helper.md }, { ServerUrlHelper: helpers/server-url-helper.md }] }
    - { Emitters: emitters.md }
    - { Examples: usage-examples.md }
    - { Cookbook: cookbook.md }
site_name: zend-expressive
site_description: 'zend-expressive: PSR-7 Middleware Microframework'
repo_url: 'https://github.com/zendframework/zend-expressive'
copyright: 'Copyright (c) 2015 <a href="http://www.zend.com/">Zend Technologies USA Inc.</a>'
